name: flutter_dev_framework_example
description: Demonstrates how to use the flutter_dev_framework plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dev_framework:
    path: ../

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
        - asset: assets/fonts/NotoSansKR-Bold.otf
        - asset: assets/fonts/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Thin.otf

  uses-material-design: true
